- name: Setup Customer Chatbot Environment
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - setup_environment
    - install_dependencies
    - setup_conda
    - setup_python
    - setup_git_repo
    - setup_torchserve
    - setup_data_dir

