- name: Create Conda environment from intel_env.yml
  shell: conda env create -f {{ conda_env_file }}
  environment:
    PATH: "/opt/miniconda3/bin:{{ ansible_env.PATH }}"

- name: Find Python executable in Conda environment
  shell: /opt/miniconda3/bin/conda run -n customer_chatbot_intel which python
  register: conda_python_executable

- name: Install pip in Conda environment
  shell: /opt/miniconda3/bin/conda run -n customer_chatbot_intel python -m ensurepip

- name: Install additional Python packages in Conda environment
  shell: /opt/miniconda3/envs/customer_chatbot_intel/bin/pip install torch-model-archiver captum
